---
abstract: 'VentraIP Wholesale SSL API'
author:
  - 'VentraIP Wholesale <customercare@ventraipwholesale.com.au>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-WholesaleSystem
requires:
  SOAP::Lite: 0
resources:
  repository: git://github.com/fayland/Net-WholesaleSystem.git
version: 0.01
